name: "avr-studio-test"

on:
  push:
    branches:
      - "test-avr-studio"

jobs:
  avr-studio-install:
    name: "avr-studio-install"
    runs-on: "windows-2016"
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          install: psmisc
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            as-installer-7.0.2389-full.exe
          key: 7.0.2389
      - name: "download-installer"
        shell: msys2 {0}
        run: |
          if ! [ -e as-installer-7.0.2389-full.exe ] ; then
              curl -L -f -o as-installer-7.0.2389-full.exe http://studio.download.atmel.com/7.0.2389/as-installer-7.0.2389-full.exe
          fi
      - name: "install"
        shell: msys2 {0}
        timeout-minutes: 5
        run: |
          set -x
          ./as-installer-7.0.2389-full.exe -passive -norestart -log install.log &
          pid=$!
          sleep 5
          ps -W
          while kill -0 $pid ; do
              #killall drvinst.exe || true
              taskkill /im drvinst.exe
              sleep 5
          done
          wait $pid
      - name: "check files"
        if: ${{ always() }}
        shell: msys2 {0}
        run: |
          set -x
          ps -W
          cat install.log || true
          ls
          ls "C:\\"
          ls "C:\\Program Files\\"
          ls "C:\\Program Files (x86)\\"
