name: "Container-test"

on:
  push:
    branches:
      - "test-container"

jobs:
  test-normal:
    name: Test normal
    runs-on: "ubuntu-latest"
    steps:
      - name: Check system
        run: |
          cat /etc/os-release || true
          lsb_release || true
          id
          pwd
          ls -lah

  test-container:
    name: Test container
    runs-on: "ubuntu-latest"
    container: centos:6
    steps:
      - name: Check system
        run: |
          cat /etc/redhat-release
          id
          pwd
          ls -lah

