name: "Container-test"

on:
  push:
    branches:
      - "test-container"

jobs:
  test-normal:
    name: Test normal
    runs-on: "ubuntu-latest"
    steps:
      - name: Check system
        run: |
          cat /etc/os-release || true
          lsb_release || true
          id
          pwd
          ls -lah

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer
  test-container:
    name: Test container
    runs-on: "ubuntu-latest"
    container: i386/centos:6
    steps:
      - name: Check system
        run: |
          cat /etc/redhat-release
          id
          pwd
          ls -lah

  test-container-2:
    name: Test container 2
    runs-on: "ubuntu-latest"
    container: debian:9
    steps:
      - name: Check system
        run: |
          cat /etc/os-release || true
          lsb_release || true
          id
          pwd
          ls -lah